version: 0.0
os: linux
files:
  - source: deploy
    destination: /home/ubuntu/app/deploy
hooks:
  BeforeInstall:
    - location: deploy/scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/scripts/start_docker.sh
      timeout: 300
      runas: root